mode: dev
connections:
  database:
    prod:
      scheme: postgres
      host: localhost
      username: root
      password: root
      dbname: amigo_servers
    dev:
      scheme: mysql
      host: localhost
      username: root
      password: root
      dbname: amigo_servers