version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amigo_servers
    ports:
      - "3306:3306"
    volumes:
      - ./database/db.sql:/db.sql
  pma:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      PMA_HOST: db
    ports:
      - "80:80"