# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7.30
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: amigo_servers
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: amigo-servers-jar-zip
          path: /home/runner/work/amigo-servers/amigo-servers/target/amigoservers-backend-*.jar