# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk:15-jdk-buster

    services:
      mysql:
        image: mysql:5.7.30
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: amigo_servers

    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
      run: apt install maven && mvn -B package --file pom.xml